/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface KHubLinks {
        "lList": string;
    }
    interface KHubTiles {
        "tList": string;
    }
}
declare global {
    interface HTMLKHubLinksElement extends Components.KHubLinks, HTMLStencilElement {
    }
    var HTMLKHubLinksElement: {
        prototype: HTMLKHubLinksElement;
        new (): HTMLKHubLinksElement;
    };
    interface HTMLKHubTilesElement extends Components.KHubTiles, HTMLStencilElement {
    }
    var HTMLKHubTilesElement: {
        prototype: HTMLKHubTilesElement;
        new (): HTMLKHubTilesElement;
    };
    interface HTMLElementTagNameMap {
        "k-hub-links": HTMLKHubLinksElement;
        "k-hub-tiles": HTMLKHubTilesElement;
    }
}
declare namespace LocalJSX {
    interface KHubLinks {
        "lList"?: string;
    }
    interface KHubTiles {
        "tList"?: string;
    }
    interface IntrinsicElements {
        "k-hub-links": KHubLinks;
        "k-hub-tiles": KHubTiles;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "k-hub-links": LocalJSX.KHubLinks & JSXBase.HTMLAttributes<HTMLKHubLinksElement>;
            "k-hub-tiles": LocalJSX.KHubTiles & JSXBase.HTMLAttributes<HTMLKHubTilesElement>;
        }
    }
}
